[versions]
junit = "6.0.1"
kotlin = "2.2.21"


[libraries]
# org.junit - JUnit
# https://github.com/junit-team/junit5
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }


[plugins]
# com.github.gmazzo.buildconfig - gradle-buildconfig-plugin
# https://github.com/gmazzo/gradle-buildconfig-plugin
gradle-buildconfig = { id = "com.github.gmazzo.buildconfig", version = "6.0.6" }

# com.gradle.plugin-publish - plugin-publish
plugin-publish = { id = "com.gradle.plugin-publish", version = "2.0.0" }

# io.github.themrmilchmann.gradle.toolchainswitches:gradle-toolchain-switches - Gradle Toolchain Switches Plugin
# https://github.com/TheMrMilchmann/gradle-toolchain-switches
gradle-toolchain-switches = { id = "io.github.themrmilchmann.toolchain-switches", version = "0.3.0" }

# org.jetbrains.kotlinx.binary-compatibility-validator - binary-compatibility-validator
# https://github.com/Kotlin/binary-compatibility-validator
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.18.1" }

# org.jetbrains.kotlin - Kotlin
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-samwithreceiver = { id = "org.jetbrains.kotlin.plugin.sam.with.receiver", version.ref = "kotlin" }